server:
  port: 25489
spring:
  application:
    name: fraud
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: frauddb
      port: 27017
      host: localhost
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      instance:
        instance-id: ${spring.application.name}:${instanceId:${random.value}}