server:
  port: 6497
spring:
  application:
    name: customer-ms

  datasource:
    url: jdbc:postgresql://localhost:5432/customer-ms
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: shahin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      instance:
        instance-id: ${spring.application.name}:${instanceId:${random.value}}